### ISSUE TITLE
Please upgrade CSS to Tailwind 3

### ISSUE THREAD

**Issue by Monomachus** [waynestate/nova-text-copy-field#4]
Hello,

First of all, thank you for the package.

I see CSS classes as text-danger and text-success which were transformed to text-red-500 and text-green-500. 
Also, there's mx-3 class that is not supported by default in Nova 4 (please check the issue on their end related to that - https://github.com/laravel/nova-issues/issues/4061), however, the ml-3 and mr-3 are supported. 
So maybe it's easier to replace those shortenings with the full classes - for example, replace mx-3 with ml-3 and mr-3.

Let me know if you have any questions.

Thank you.

**Comment by chrispelzer** [comment]
Thank you, I'll take a look at it later today.

**Comment by chrispelzer** [comment]
This has been fixed on [v2.0.2](https://github.com/waynestate/nova-text-copy-field/releases/tag/v2.0.2)

<img width="545" alt="Screen Shot 2022-10-26 at 7 02 54 PM" src="https://user-images.githubusercontent.com/636531/198154808-e51c97b0-2894-42d9-a3d8-59352fc14f28.png">
