### ISSUE TITLE
As a user I want to see '—' in case of null value

### ISSUE THREAD

**Issue by nastoychev** [waynestate/nova-text-copy-field#6]
## Preflight
- [x] I have searched the repo for this duplicates

##  Description
Somehow if the copyValue, or Closure return is null, instead of seeing copy icon I think will be better if the user see '—'.
![image](https://user-images.githubusercontent.com/41673191/200371972-123d6bf7-c68f-4911-88c4-b6552a3327eb.png)

**Comment by chrispelzer** [comment]
v2.0.3 will now display a em dash in place if the value is null, it will also not show the copy button anymore.
https://github.com/waynestate/nova-text-copy-field/releases/tag/v2.0.3
